# Generated by Django 5.2.2 on 2025-06-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
